### ISSUE TITLE
NGX version

### ISSUE THREAD

**Issue by fergardi** [ingmarh/scroll-shadow-element#4]
Hello!

Very interesting plugin. Have you though about releasing an Angular version?

Thanks.

**Comment by ingmarh** [comment]
Hello @fergardi,

There are no plans to release any version that is specific to a framework or library (including React, Angular etc.) because `<scroll-shadow>` is a custom element/standalone web component and should work with any framework or library. In general, [Angular should have good support for custom elements](https://custom-elements-everywhere.com/).

I am successfully using it in React applications, and it should also work with Angular, just like other HTML elements. It only needs to be loaded in the browser as part of your app bundle or with a simple `<script>` tag ([see these examples](https://github.com/ingmarh/scroll-shadow-element#installation)). Let me know if there are any issues when using inside an Angular project and I can see if I can help.
